server.port=3004 

spring.mongodb.uri=mongodb+srv://nguyenhung2004200_db_user:W87UoUWquGGfbjXv@cluster1.gypblkl.mongodb.net/OrderServiceDatabase?appName=Cluster1

order-service.url=http://192.168.1.105:3003